cmake_minimum_required(VERSION 3.19)

project(RollScript
    VERSION 0.1.0
    LANGUAGES C CXX
)

# -----------------------------------------------------------------------------
# Core Library
# -----------------------------------------------------------------------------

add_subdirectory(Core)


# -----------------------------------------------------------------------------
# Application
# -----------------------------------------------------------------------------

add_subdirectory(Application)


# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------
# --- Printers ----------------------------------------------------------------
add_subdirectory(Plugins/Printers/DymoLabelPoint350)

# --- Features ----------------------------------------------------------------
# add_subdirectory(Plugins/Features/LabelBlockText)