name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Release version (e.g. 0.1.0)'
                required: true
                type: string

jobs:
    build:
        uses: ./.github/workflows/build-ubuntu-24.04-reusable.yml
